### ISSUE TITLE
Database dump

### ISSUE THREAD

**Issue by 5knnbdwm** [notshi/dquery#2]
Hey, when trying to download the PostgreSQL Dump i get a 404 error.

**Comment by notshi** [comment]
Hey, thanks for letting me - will take a look at what's happening there.

**Comment by xriss** [comment]
Sorry old docs I stopped generating that one a long time ago as it was a bit large/slow and wasn't much use.

Just use http://d-portal.org/db/dstore.pg as its only going to work with postgres anyhow.

**Comment by 5knnbdwm** [comment]
Okay. Thanks for checking

**Comment by agombert** [comment]
Hey, 

The dump has a 403 error:

![Capture d’écran 2023-11-17 à 09 21 43](https://github.com/notshi/dquery/assets/17645711/8e2073be-c4f2-492d-afbf-bbc503bb31bb)

Any idea how to get it ? Other questions, is it possible to have updated version or do you need to download each time the data ?

**Comment by notshi** [comment]
Hey, thanks for letting me know ~ will take a look at what's happening there.

We've recently been changing servers so we may have missed something.

**Comment by notshi** [comment]
The [database dump link](http://d-portal.org/db/dstore.pg) is now fixed - we just missed a permission on the web server.

> Any idea how to get it ? Other questions, is it possible to have updated version or do you need to download each time the data ?

We start a new database every night so we don't have diffs.
A full import takes as much time as an incremental update so we didn't see a need for it.
