### ISSUE TITLE
Server down ? 

### ISSUE THREAD

**Issue by agombert** [notshi/dquery#3]
When trying to download data. Is there some maintenance ?

![Capture d’écran 2023-11-16 à 15 42 27](https://github.com/notshi/dquery/assets/17645711/58223b9e-7adc-4fbf-9ce5-e05320974a55)

Best, 

Arnault

**Comment by notshi** [comment]
Thanks for letting us know - we've been changing servers recently and you probably caught us in the middle of it.

Related to https://github.com/notshi/dquery/issues/2

**Comment by notshi** [comment]
Hi @agombert - is this still an issue for you?

**Comment by agombert** [comment]
Hey @notshi I don't think so I've been downloading it lately quite easily in my pipeline, so let me close this !
